# APP
# IMAGE
# TAG
# FQDN
# NAMESPACE
---
apiVersion: v1
kind: Namespace
metadata:
  name: NAMESPACE
  labels:
    project: APP
---
apiVersion: v1
kind: Service
metadata:
  name: APP
  namespace: NAMESPACE
  labels:
    app: APP
spec:
  selector:
    app: APP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: APP
  namespace: NAMESPACE
  labels:
    app: APP
spec:
  replicas: 1
  selector:
    matchLabels:
      app: APP
  template:
    metadata:
      labels:
        app: APP
    spec:
      volumes:
      containers:
        - name: APP
          image: IMAGE:TAG
          imagePullPolicy: Always
          ports:
            - name: tcp
              containerPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: APP
  namespace: NAMESPACE
  labels:
    app: APP
spec:
  rules:
    - host: FQDN
      http:
        paths:
          - backend:
              serviceName: APP
              servicePort: 8080
